export const TOKEN = 'token';
export const REFRESH_TOKEN = 'refresh_token';
export const ID_TOKEN = 'id_token';
export const PRODUCT_STATE = 'product-state';
export const REFERRAL = 'referral';
export const REDIRECT_URL = 'redirect-url';

export const CLEAR = 'CLEAR';

// upload constants
export const GET_UPLOADS_SUCCESS = 'GET_UPLOADS_SUCCESS';
export const GET_UPLOADS_FAILURE = 'GET_UPLOADS_FAILURE';

export const BRANDING_REQUEST = 'BRANDING_REQUEST';
export const GET_BRANDING_SUCCESS = 'GET_BRANDING_SUCCESS';
export const BRANDING_FAILURE = 'BRANDING_FAILURE';

export const CONFIGURATION_REQUEST = 'CONFIGURATION_REQUEST';
export const GET_CONFIGURATION_SUCCESS = 'GET_CONFIGURATION_SUCCESS';
export const CONFIGURATION_FAILURE = 'CONFIGURATION_FAILURE';

export const FORMS_REQUEST = 'forms/in-progress';
export const FORMS_FAILURE = 'forms/failed';
export const FORM_FETCHED = 'forms/got-by-id';

export const CARD_REQUEST = 'card/in-progress';
export const CARD_FAILURE = 'card/failed';
export const CARD_FETCHED = 'card/fetched';
export const CARD_CREATED = 'card/created';

export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';

export const GET_STATE_MACHINE_REQUEST = 'GET_STATE_MACHINE_REQUEST';
export const GET_STATE_MACHINE_SUCCESS = 'GET_STATE_MACHINE_SUCCESS';
export const GET_STATE_MACHINE_FAILURE = 'GET_STATE_MACHINE_FAILURE';

export const APPLICATION_REQUEST = 'APPLICATION_REQUEST';
export const GET_APPLICATIONS_SUCCESS = 'GET_APPLICATIONS_SUCCESS';
export const START_APPLICATION_SUCCESS = 'START_APPLICATION_SUCCESS';
export const GET_APPLICATION_BY_ID_SUCCESS = 'GET_APPLICATION_BY_ID_SUCCESS';
export const UPDATE_APPLICATION_BY_ID_SUCCESS =
  'UPDATE_APPLICATION_BY_ID_SUCCESS';
export const APPLICATION_FAILURE = 'APPLICATION_FAILURE';
export const SET_APPLICATION_REFERRAL_SUCCESS =
  'SET_APPLICATION_REFERRAL_SUCCESS';
export const REMOVE_APPLICATION_SUCCESS = 'REMOVE_APPLICATION_SUCCESS';

// stage

export const REQUEST_SAVE_STAGE = 'REQUEST_SAVE_STAGE';
export const STAGE_SAVED = 'STAGE_SAVED';
export const FAILED_SAVE_STAGE = 'FAILED_SAVE_STAGE';
export const REQUEST_RESOLVE_STAGE_DATA = 'RESOLVE_STAGE_DATA';
export const STAGE_DATA_RESOLVED = 'STAGE_DATA_RESOLVED';
export const FAILED_RESOLVE_STAGE_DATA = 'FAILED_RESOLVE_STAGE_DATA';

// auth
export const AUTH_START_VERIFY = `AUTH_START_VERIFY`;
export const AUTH_SUCCESS_VERIFY = `AUTH_SUCCESS_VERIFY`;
export const AUTH_FAILED_VERIFY = `AUTH_FAILED_VERIFY`;
export const LOGOUT = `LOGOUT`;
